"""Install the first a00 workbench UI in the existing console."""
from pathlib import Path

console_path = Path(__file__).resolve().parents[2] / "02_Futures_Lakehouse/operations/console.py"
source = console_path.read_text(encoding="utf-8")
start = source.index("        maintenance_layout = QVBoxLayout(self.maintenance_tab)")
end = source.index('        theme_name = self.preferences.value', start)
source = source[:start] + '''        a00_layout = QVBoxLayout(self.a00_page)
        a00_layout.setContentsMargins(0, 0, 0, 0)
        a00_layout.setSpacing(10)
        a00_header = QFrame()
        a00_header.setObjectName("card")
        a00_header_layout = QVBoxLayout(a00_header)
        a00_header_layout.setContentsMargins(18, 14, 18, 14)
        title_row = QHBoxLayout()
        self.a00_code = QLabel()
        self.a00_code.setObjectName("badge")
        title_row.addWidget(self.a00_code)
        self.a00_title = QLabel()
        self.a00_title.setObjectName("heading")
        title_row.addWidget(self.a00_title, 1)
        self.a00_state = QLabel("未运行")
        self.a00_state.setObjectName("badge")
        title_row.addWidget(self.a00_state)
        a00_header_layout.addLayout(title_row)
        self.maintenance_description = QLabel()
        self.maintenance_description.setWordWrap(True)
        a00_header_layout.addWidget(self.maintenance_description)
        self.maintenance_command = QLabel()
        self.maintenance_command.setObjectName("code")
        self.maintenance_command.setWordWrap(True)
        self.maintenance_command.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
        a00_header_layout.addWidget(self.maintenance_command)
        tools_actions = QHBoxLayout()
        self.a00_source_button = QPushButton("打开源码")
        self.a00_source_button.clicked.connect(self.open_a00_source)
        tools_actions.addWidget(self.a00_source_button)
        self.reload_button = QPushButton("重读采集参数")
        self.reload_button.clicked.connect(self.reload_catalog)
        tools_actions.addWidget(self.reload_button)
        tools_actions.addStretch()
        self.a00_interrupt_button = QPushButton("中断本批次")
        self.a00_interrupt_button.setObjectName("dangerButton")
        self.a00_interrupt_button.clicked.connect(self.interrupt)
        tools_actions.addWidget(self.a00_interrupt_button)
        self.run_tool_button = QPushButton("执行检查  →")
        self.run_tool_button.setObjectName("accent")
        self.run_tool_button.clicked.connect(self.run_maintenance)
        tools_actions.addWidget(self.run_tool_button)
        a00_header_layout.addLayout(tools_actions)
        a00_layout.addWidget(a00_header)

        self.a00_runtime_panel = QWidget()
        runtime_layout = QVBoxLayout(self.a00_runtime_panel)
        runtime_layout.setContentsMargins(0, 0, 0, 0)
        runtime_layout.setSpacing(8)
        self.a00_position = QLabel("尚未运行 · 执行后显示真实计数")
        self.a00_position.setObjectName("section")
        self.a00_position.setWordWrap(True)
        runtime_layout.addWidget(self.a00_position)
        metrics_row = QHBoxLayout()
        self.a00_metrics = {}
        for key, title in (("total", "本步总量"), ("completed", "已处理"), ("remaining", "剩余"), ("failed", "异常项目")):
            card = QFrame()
            card.setObjectName("card")
            card_layout = QVBoxLayout(card)
            card_layout.setContentsMargins(14, 8, 14, 8)
            label = QLabel(title)
            label.setObjectName("muted")
            card_layout.addWidget(label)
            value_label = QLabel("—")
            value_label.setObjectName("metric")
            card_layout.addWidget(value_label)
            self.a00_metrics[key] = value_label
            metrics_row.addWidget(card, 1)
        runtime_layout.addLayout(metrics_row)
        self.a00_phases_layout = QHBoxLayout()
        self.a00_phase_widgets = {}
        runtime_layout.addLayout(self.a00_phases_layout)
        self.a00_health = QLabel("耗时 —　·　心跳 —")
        self.a00_health.setObjectName("muted")
        self.a00_health.setWordWrap(True)
        runtime_layout.addWidget(self.a00_health)
        self.a00_error = QLabel()
        self.a00_error.setObjectName("error")
        self.a00_error.setWordWrap(True)
        self.a00_error.setTextFormat(Qt.TextFormat.PlainText)
        self.a00_error.hide()
        runtime_layout.addWidget(self.a00_error)

        detail_split = QSplitter(Qt.Orientation.Vertical)
        detail_split.setChildrenCollapsible(False)
        self.a00_results = QTreeWidget()
        self.a00_results.setRootIsDecorated(False)
        self.a00_results.setAlternatingRowColors(True)
        self.a00_results.setMinimumHeight(90)
        detail_split.addWidget(self.a00_results)
        log_panel = QWidget()
        log_layout = QVBoxLayout(log_panel)
        log_layout.setContentsMargins(0, 0, 0, 0)
        log_heading = QHBoxLayout()
        self.a00_log_location = QLabel("实时日志 · 尚未运行")
        self.a00_log_location.setObjectName("muted")
        log_heading.addWidget(self.a00_log_location, 1)
        self.a00_follow_log = QCheckBox("跟随末尾")
        self.a00_follow_log.setChecked(True)
        log_heading.addWidget(self.a00_follow_log)
        log_layout.addLayout(log_heading)
        self.a00_logs = QPlainTextEdit()
        self.a00_logs.setReadOnly(True)
        self.a00_logs.setMaximumBlockCount(4000)
        self.a00_logs.setMinimumHeight(90)
        self.a00_logs.setPlaceholderText("点击执行后，原始 stdout / stderr 将在这里持续显示。")
        log_layout.addWidget(self.a00_logs)
        detail_split.addWidget(log_panel)
        detail_split.setSizes([180, 160])
        runtime_layout.addWidget(detail_split, 1)
        a00_layout.addWidget(self.a00_runtime_panel, 1)
        self.a00_reference = QTextBrowser()
        self.a00_reference.setOpenExternalLinks(False)
        a00_layout.addWidget(self.a00_reference, 1)

''' + source[end:]
console_path.write_text(source, encoding="utf-8", newline="\n")
